module.exports = [
    {   
        "email": "john.doe@example.com",
        "password": "password123",
        "name": "John",
        "surname": "Doe",
        "anrede": "Mr.",
        "birthdate": "1980-08-24",
        "mobile": "+1 202-555-0191",
        "city": "New York",
        "linkedIn": "https://www.linkedin.com/in/johndoe",
        "european": true,
        "university": "Harvard University",
        "subject": "Computer Science",
        "studyLevel": "Master",
        "uniStartDate": "2002-09-01",   
        "fileNameMatr": "",
        "bucketPathMatr": "",
        "typeMatr": "application/pdf",     
        "fileNameEngl": "",
        "bucketPathEngl": "",
        "typeEngl": "application/pdf",
        "englProf": "CPE",
        "levelEngl": 7,
        "deleted": false
    },
    {   
        "email": "robert.smith@example.com",
        "password": "robertpassword",
        "name": "Robert",
        "surname": "Smith",
        "anrede": "Mr.",
        "birthdate": "1981-02-12",
        "mobile": "+1 202-555-0141",
        "city": "Chicago",
        "linkedIn": "https://www.linkedin.com/in/robertsmith",
        "european": true,
        "university": "Stanford University",
        "subject": "Business Administration",
        "studyLevel": "Bachelor",
        "uniStartDate": "2001-09-01",   
        "fileNameMatr": "",
        "bucketPathMatr": "",
        "typeMatr": "application/pdf",     
        "fileNameEngl": "",
        "bucketPathEngl": "",
        "typeEngl": "application/pdf",
        "englProf": "TEOFL",
        "levelEngl": 6,
        "deleted": false
    },

    {   
        "email": "mary.johnson@example.com",
        "password": "marypassword",
        "name": "Mary",
        "surname": "Johnson",
        "anrede": "Mrs.",
        "birthdate": "1985-07-18",
        "mobile": "+1 415-555-0116",
        "city": "San Francisco",
        "linkedIn": "https://www.linkedin.com/in/maryjohnson",
        "european": false,
        "university": "University of California, Berkeley",
        "subject": "Psychology",
        "studyLevel": "Master",
        "uniStartDate": "2005-09-01",   
        "fileNameMatr": "",
        "bucketPathMatr": "",
        "typeMatr": "application/pdf",     
        "fileNameEngl": "",
        "bucketPathEngl": "",
        "typeEngl": "application/pdf",
        "englProf": "IELTS",
        "levelEngl": 8,
        "deleted": false
    },

    {   
        "email": "james.williams@example.com",
        "password": "jamespassword",
        "name": "James",
        "surname": "Williams",
        "anrede": "Mr.",
        "birthdate": "1983-12-17",
        "mobile": "+1 510-555-0158",
        "city": "Los Angeles",
        "linkedIn": "https://www.linkedin.com/in/jameswilliams",
        "european": true,
        "university": "University of Southern California",
        "subject": "Engineering",
        "studyLevel": "PHD",
        "uniStartDate": "2004-09-01",   
        "fileNameMatr": "",
        "bucketPathMatr": "",
        "typeMatr": "application/pdf",     
        "fileNameEngl": "",
        "bucketPathEngl": "",
        "typeEngl": "application/pdf",
        "englProf": "CPE",
        "levelEngl": 7,
        "deleted": false
    },
{
    "email": "patricia.jones@example.com",
    "password": "passwordPatricia",
    "name": "Patricia",
    "surname": "Jones",
    "anrede": "Mrs.",
    "birthdate": "1990-10-02",
    "mobile": "+1 210-555-0141",
    "city": "Houston",
    "linkedIn": "https://www.linkedin.com/in/patriciajones",
    "european": false,
    "university": "Rice University",
    "subject": "Biochemistry",
    "studyLevel": "Bachelor",
    "uniStartDate": "2009-09-01",   
    "fileNameMatr": "",
    "bucketPathMatr": "",
    "typeMatr": "application/pdf",     
    "fileNameEngl": "",
    "bucketPathEngl": "",
    "typeEngl": "application/pdf",
    "englProf": "CAE",
    "levelEngl": 9,
    "deleted": false
},

{
    "email": "michael.brown@example.com",
    "password": "passwordMichael",
    "name": "Michael",
    "surname": "Brown",
    "anrede": "Mr.",
    "birthdate": "1988-06-23",
    "mobile": "+1 310-555-0190",
    "city": "Dallas",
    "linkedIn": "https://www.linkedin.com/in/michaelbrown",
    "european": true,
    "university": "University of Texas at Dallas",
    "subject": "Physics",
    "studyLevel": "Master",
    "uniStartDate": "2007-09-01",   
    "fileNameMatr": "",
    "bucketPathMatr": "",
    "typeMatr": "application/pdf",     
    "fileNameEngl": "",
    "bucketPathEngl": "",
    "typeEngl": "application/pdf",
    "englProf": "TEOFL",
    "levelEngl": 7,
    "deleted": false
},

{
    "email": "jennifer.davis@example.com",
    "password": "passwordJennifer",
    "name": "Jennifer",
    "surname": "Davis",
    "anrede": "Mrs.",
    "birthdate": "1992-12-10",
    "mobile": "+1 214-555-0187",
    "city": "Atlanta",
    "linkedIn": "https://www.linkedin.com/in/jenniferdavis",
    "european": false,
    "university": "Emory University",
    "subject": "Music",
    "studyLevel": "PHD",
    "uniStartDate": "2012-09-01",   
    "fileNameMatr": "",
    "bucketPathMatr": "",
    "typeMatr": "application/pdf",     
    "fileNameEngl": "",
    "bucketPathEngl": "",
    "typeEngl": "application/pdf",
    "englProf": "CPE",
    "levelEngl": 6,
    "deleted": false
    },
{
    "email": "thomas.miller@example.com",
    "password": "passwordThomas",
    "name": "Thomas",
    "surname": "Miller",
    "anrede": "Mr.",
    "birthdate": "1986-03-14",
    "mobile": "+1 512-555-0132",
    "city": "Austin",
    "linkedIn": "https://www.linkedin.com/in/thomasmiller",
    "european": true,
    "university": "University of Texas at Austin",
    "subject": "Architecture",
    "studyLevel": "Bachelor",
    "uniStartDate": "2005-09-01",
    "fileNameMatr": "",
    "bucketPathMatr": "",
    "typeMatr": "application/pdf",
    "fileNameEngl": "",
    "bucketPathEngl": "",
    "typeEngl": "application/pdf",
    "englProf": "CAE",
    "levelEngl": 8,
    "deleted": false
},
{
    "email": "elizabeth.moore@example.com",
    "password": "passwordElizabeth",
    "name": "Elizabeth",
    "surname": "Moore",
    "anrede": "Mrs.",
    "birthdate": "1984-07-20",
    "mobile": "+1 415-555-0148",
    "city": "San Diego",
    "linkedIn": "https://www.linkedin.com/in/elizabethmoore",
    "european": false,
    "university": "University of California, San Diego",
    "subject": "Marketing",
    "studyLevel": "Master",
    "uniStartDate": "2003-09-01",
    "fileNameMatr": "",
    "bucketPathMatr": "",
    "typeMatr": "application/pdf",
    "fileNameEngl": "",
    "bucketPathEngl": "",
    "typeEngl": "application/pdf",
    "englProf": "TEOFL",
    "levelEngl": 6,
    "deleted": false
},
{
    "email": "edward.taylor@example.com",
    "password": "passwordEdward",
    "name": "Edward",
    "surname": "Taylor",
    "anrede": "Mr.",
    "birthdate": "1982-11-28",
    "mobile": "+1 619-555-0123",
    "city": "San Francisco",
    "linkedIn": "https://www.linkedin.com/in/edwardtaylor",
    "european": true,
    "university": "San Francisco State University",
    "subject": "Journalism",
    "studyLevel": "PHD",
    "uniStartDate": "2001-09-01",
    "fileNameMatr": "",
    "bucketPathMatr": "",
    "typeMatr": "application/pdf",
    "fileNameEngl": "",
    "bucketPathEngl": "",
    "typeEngl": "application/pdf",
    "englProf": "CPE",
    "levelEngl": 7,
    "deleted": false
    },
{
    "email": "maria.garcia@example.com",
    "password": "passwordMaria",
    "name": "Maria",
    "surname": "Garcia",
    "anrede": "Mrs.",
    "birthdate": "1989-05-22",
    "mobile": "+1 305-555-0122",
    "city": "Los Angeles",
    "linkedIn": "https://www.linkedin.com/in/mariagarcia",
    "european": true,
    "university": "University of Southern California",
    "subject": "Multimedia",
    "studyLevel": "Master",
    "uniStartDate": "2008-09-01",
    "fileNameMatr": "",
    "bucketPathMatr": "",
    "typeMatr": "application/pdf",
    "fileNameEngl": "",
    "bucketPathEngl": "",
    "typeEngl": "application/pdf",
    "englProf": "CAE",
    "levelEngl": 8,
    "deleted": false
},
{
    "email": "jose.rodriguez@example.com",
    "password": "passwordJose",
    "name": "Jose",
    "surname": "Rodriguez",
    "anrede": "Mr.",
    "birthdate": "1987-12-15",
    "mobile": "+1 213-555-0103",
    "city": "New York",
    "linkedIn": "https://www.linkedin.com/in/joserodriguez",
    "european": false,
    "university": "Columbia University",
    "subject": "Art History",
    "studyLevel": "PHD",
    "uniStartDate": "2010-09-01",
    "fileNameMatr": "",
    "bucketPathMatr": "",
    "typeMatr": "application/pdf",
    "fileNameEngl": "",
    "bucketPathEngl": "",
    "typeEngl": "application/pdf",
    "englProf": "TEOFL",
    "levelEngl": 7,
    "deleted": false
    },
{
    "email": "amy.wilson@example.com",
    "password": "passwordAmy",
    "name": "Amy",
    "surname": "Wilson",
    "anrede": "Mrs.",
    "birthdate": "1990-03-05",
    "mobile": "+1 213-555-0120",
    "city": "Los Angeles",
    "linkedIn": "https://www.linkedin.com/in/amywilson",
    "european": true,
    "university": "University of Southern California",
    "subject": "Molecular Biology",
    "studyLevel": "Bachelor",
    "uniStartDate": "2008-09-01",
    "fileNameMatr": "",
    "bucketPathMatr": "",
    "typeMatr": "application/pdf",
    "fileNameEngl": "",
    "bucketPathEngl": "",
    "typeEngl": "application/pdf",
    "englProf": "TEOFL",
    "levelEngl": 5,
    "deleted": false
},
{
    "email": "william.jackson@example.com",
    "password": "passwordWilliam",
    "name": "William",
    "surname": "Jackson",
    "anrede": "Mr.",
    "birthdate": "1989-10-09",
    "mobile": "+1 415-555-0135",
    "city": "San Francisco",
    "linkedIn": "https://www.linkedin.com/in/williamjackson",
    "european": false,
    "university": "San Francisco State University",
    "subject": "Computer Engineering",
    "studyLevel": "Master",
    "uniStartDate": "2007-09-01",
    "fileNameMatr": "",
    "bucketPathMatr": "",
    "typeMatr": "application/pdf",
    "fileNameEngl": "",
    "bucketPathEngl": "",
    "typeEngl": "application/pdf",
    "englProf": "IELTS",
    "levelEngl": 7,
    "deleted": false
},
{
    "email": "sarah.martin@example.com",
    "password": "passwordSarah",
    "name": "Sarah",
    "surname": "Martin",
    "anrede": "Mrs.",
    "birthdate": "1992-07-19",
    "mobile": "+1 619-555-0147",
    "city": "San Diego",
    "linkedIn": "https://www.linkedin.com/in/sarahmartin",
    "european": false,
    "university": "University of California, San Diego",
    "subject": "Psychology",
    "studyLevel": "PHD",
    "uniStartDate": "2010-09-01",
    "fileNameMatr": "",
    "bucketPathMatr": "",
    "typeMatr": "application/pdf",
    "fileNameEngl": "",
    "bucketPathEngl": "",
    "typeEngl": "application/pdf",
    "englProf": "TEOFL",
    "levelEngl": 9,
    "deleted": false
    },
{
    "email": "emily.anderson@example.com",
    "password": "passwordEmily",
    "name": "Emily",
    "surname": "Anderson",
    "anrede": "Mrs.",
    "birthdate": "1991-09-08",
    "mobile": "+1 202-555-0176",
    "city": "Washington D.C.",
    "linkedIn": "https://www.linkedin.com/in/emilyanderson",
    "european": false,
    "university": "Georgetown University",
    "subject": "International Relations",
    "studyLevel": "Master",
    "uniStartDate": "2010-09-01",
    "fileNameMatr": "",
    "bucketPathMatr": "",
    "typeMatr": "application/pdf",
    "fileNameEngl": "",
    "bucketPathEngl": "",
    "typeEngl": "application/pdf",
    "englProf": "TOEFL",
    "levelEngl": 8,
    "deleted": false
},
{
    "email": "daniel.nguyen@example.com",
    "password": "passwordDaniel",
    "name": "Daniel",
    "surname": "Nguyen",
    "anrede": "Mr.",
    "birthdate": "1993-05-12",
    "mobile": "+1 415-555-0164",
    "city": "San Francisco",
    "linkedIn": "https://www.linkedin.com/in/danielnguyen",
    "european": false,
    "university": "University of California, Berkeley",
    "subject": "Economics",
    "studyLevel": "Bachelor",
    "uniStartDate": "2011-09-01",
    "fileNameMatr": "",
    "bucketPathMatr": "",
    "typeMatr": "application/pdf",
    "fileNameEngl": "",
    "bucketPathEngl": "",
    "typeEngl": "application/pdf",
    "englProf": "IELTS",
    "levelEngl": 7,
    "deleted": false
},
{
    "email": "alexander.johnson@example.com",
    "password": "passwordAlexander",
    "name": "Alexander",
    "surname": "Johnson",
    "anrede": "Mr.",
    "birthdate": "1987-12-03",
    "mobile": "+1 310-555-0198",
    "city": "Los Angeles",
    "linkedIn": "https://www.linkedin.com/in/alexanderjohnson",
    "european": true,
    "university": "University of California, Los Angeles",
    "subject": "Film Studies",
    "studyLevel": "Master",
    "uniStartDate": "2006-09-01",
    "fileNameMatr": "",
    "bucketPathMatr": "",
    "typeMatr": "application/pdf",
    "fileNameEngl": "",
    "bucketPathEngl": "",
    "typeEngl": "application/pdf",
    "englProf": "CPE",
    "levelEngl": 8,
    "deleted": false
},
{
    "email": "olivia.thomas@example.com",
    "password": "passwordOlivia",
    "name": "Olivia",
    "surname": "Thomas",
    "anrede": "Mrs.",
    "birthdate": "1994-04-25",
    "mobile": "+1 512-555-0119",
    "city": "Austin",
    "linkedIn": "https://www.linkedin.com/in/oliviathomas",
    "european": true,
    "university": "University of Texas at Austin",
    "subject": "Sociology",
    "studyLevel": "Bachelor",
    "uniStartDate": "2013-09-01",
    "fileNameMatr": "",
    "bucketPathMatr": "",
    "typeMatr": "application/pdf",
    "fileNameEngl": "",
    "bucketPathEngl": "",
    "typeEngl": "application/pdf",
    "englProf": "TOEFL",
    "levelEngl": 7,
    "deleted": false
},
{
    "email": "nathan.roberts@example.com",
    "password": "passwordNathan",
    "name": "Nathan",
    "surname": "Roberts",
    "anrede": "Mr.",
    "birthdate": "1990-11-14",
    "mobile": "+1 213-555-0139",
    "city": "Los Angeles",
    "linkedIn": "https://www.linkedin.com/in/nathanroberts",
    "european": false,
    "university": "University of Southern California",
    "subject": "Political Science",
    "studyLevel": "PHD",
    "uniStartDate": "2010-09-01",
    "fileNameMatr": "",
    "bucketPathMatr": "",
    "typeMatr": "application/pdf",
    "fileNameEngl": "",
    "bucketPathEngl": "",
    "typeEngl": "application/pdf",
    "englProf": "CAE",
    "levelEngl": 8,
    "deleted": false
},
{
    "email": "samantha.harris@example.com",
    "password": "passwordSamantha",
    "name": "Samantha",
    "surname": "Harris",
    "anrede": "Mrs.",
    "birthdate": "1993-08-19",
    "mobile": "+1 202-555-0182",
    "city": "Washington D.C.",
    "linkedIn": "https://www.linkedin.com/in/samanthaharris",
    "european": false,
    "university": "George Washington University",
    "subject": "Public Health",
    "studyLevel": "Master",
    "uniStartDate": "2012-09-01",
    "fileNameMatr": "",
    "bucketPathMatr": "",
    "typeMatr": "application/pdf",
    "fileNameEngl": "",
    "bucketPathEngl": "",
    "typeEngl": "application/pdf",
    "englProf": "IELTS",
    "levelEngl": 7,
    "deleted": false
},
{
    "email": "william.thompson@example.com",
    "password": "passwordWilliam",
    "name": "William",
    "surname": "Thompson",
    "anrede": "Mr.",
    "birthdate": "1988-05-28",
    "mobile": "+1 415-555-0162",
    "city": "San Francisco",
    "linkedIn": "https://www.linkedin.com/in/williamthompson",
    "european": true,
    "university": "University College London",
    "subject": "History",
    "studyLevel": "Bachelor",
    "uniStartDate": "2007-09-01",
    "fileNameMatr": "",
    "bucketPathMatr": "",
    "typeMatr": "application/pdf",
    "fileNameEngl": "",
    "bucketPathEngl": "",
    "typeEngl": "application/pdf",
    "englProf": "TOEFL",
    "levelEngl": 8,
    "deleted": false
},
{
    "email": "emily.wilson@example.com",
    "password": "passwordEmily",
    "name": "Emily",
    "surname": "Wilson",
    "anrede": "Mrs.",
    "birthdate": "1991-11-03",
    "mobile": "+1 310-555-0139",
    "city": "Los Angeles",
    "linkedIn": "https://www.linkedin.com/in/emilywilson",
    "european": false,
    "university": "University of California, Los Angeles",
    "subject": "Environmental Science",
    "studyLevel": "PHD",
    "uniStartDate": "2011-09-01",
    "fileNameMatr": "",
    "bucketPathMatr": "",
    "typeMatr": "application/pdf",
    "fileNameEngl": "",
    "bucketPathEngl": "",
    "typeEngl": "application/pdf",
    "englProf": "CAE",
    "levelEngl": 9,
    "deleted": false
},
{
    "email": "jacob.evans@example.com",
    "password": "passwordJacob",
    "name": "Jacob",
    "surname": "Evans",
    "anrede": "Mr.",
    "birthdate": "1989-07-15",
    "mobile": "+1 512-555-0157",
    "city": "Austin",
    "linkedIn": "https://www.linkedin.com/in/jacobeveans",
    "european": true,
    "university": "University of Edinburgh",
    "subject": "Literature",
    "studyLevel": "Master",
    "uniStartDate": "2008-09-01",
    "fileNameMatr": "",
    "bucketPathMatr": "",
    "typeMatr": "application/pdf",
    "fileNameEngl": "",
    "bucketPathEngl": "",
    "typeEngl": "application/pdf",
    "englProf": "CPE",
    "levelEngl": 8,
    "deleted": false
},
{
    "email": "madison.carter@example.com",
    "password": "passwordMadison",
    "name": "Madison",
    "surname": "Carter",
    "anrede": "Mrs.",
    "birthdate": "1990-02-20",
    "mobile": "+1 213-555-0143",
    "city": "Los Angeles",
    "linkedIn": "https://www.linkedin.com/in/madisoncarter",
    "european": false,
    "university": "University of Southern California",
    "subject": "Political Science",
    "studyLevel": "Bachelor",
    "uniStartDate": "2009-09-01",
    "fileNameMatr": "",
    "bucketPathMatr": "",
    "typeMatr": "application/pdf",
    "fileNameEngl": "",
    "bucketPathEngl": "",
    "typeEngl": "application/pdf",
    "englProf": "TOEFL",
    "levelEngl": 7,
    "deleted": false
}








];