
module.exports = [
{
    "name": "Techify",
    "description": "Techify is a platform that provides innovative solutions for businesses to streamline their operations and enhance productivity.",
    "motivation": "We were motivated to start Techify by the need for accessible and user-friendly technology solutions in the market.",
    "fellowReason": "Our team shares a passion for technology and a drive to make a positive impact on businesses worldwide.",
    "stage": "Seed",
    "applicationStatus": "Active",
    "foundersNumber": 3,
    "foundedYear": 2023,
    "region": "Europe",
    "batch": "W24",
    "fileNamePitch": "test.pdf",
    "bucketPathPitch": "/pitches/test.pdf",
    "typePitch": "application/pdf",
    "deleted": false
  },
  {
    "name": "GreenGenius",
    "description": "GreenGenius is dedicated to developing sustainable solutions for environmental conservation and renewable energy.",
    "motivation": "Our passion for environmental sustainability and renewable energy sources inspired us to create GreenGenius.",
    "fellowReason": "We believe in the power of technology to drive positive change and protect our planet for future generations.",
    "stage": "Idea",
    "applicationStatus": "Active",
    "foundersNumber": 2,
    "foundedYear": 2022,
    "region": "America",
    "batch": "S22",
    "fileNamePitch": "test.pdf",
    "bucketPathPitch": "/pitches/test.pdf",
    "typePitch": "application/pdf",
    "deleted": false
  },
  {
    "name": "HealthHub",
    "description": "HealthHub aims to revolutionize the healthcare industry by providing personalized and accessible healthcare solutions.",
    "motivation": "The need for accessible and affordable healthcare services drove us to create HealthHub.",
    "fellowReason": "Our team consists of healthcare professionals and technology experts who are passionate about improving healthcare outcomes.",
    "stage": "SeriesC",
    "applicationStatus": "Active",
    "foundersNumber": 4,
    "foundedYear": 2021,
    "region": "East Asia",
    "batch": "S19",
    "fileNamePitch": "test.pdf",
    "bucketPathPitch": "/pitches/test.pdf",
    "typePitch": "application/pdf",
    "deleted": false
  },
  {
    "name": "EduTech Solutions",
    "description": "EduTech Solutions offers innovative educational technology products to enhance learning experiences for students and educators.",
    "motivation": "We are motivated by the belief that education is the key to unlocking human potential and shaping a better future.",
    "fellowReason": "Our team consists of educators, technologists, and designers who are passionate about improving education through technology.",
    "stage": "SeriesA",
    "applicationStatus": "Active",
    "foundersNumber": 3,
    "foundedYear": 2020,
    "region": "Africa",
    "batch": "W20",
    "fileNamePitch": "test.pdf",
    "bucketPathPitch": "/pitches/test.pdf",
    "typePitch": "application/pdf",
    "deleted": false
  },
  {
    "name": "FoodFusion",
    "description": "FoodFusion offers a platform for food enthusiasts to discover, share, and create culinary experiences.",
    "motivation": "We are passionate about food and believe in the power of culinary experiences to bring people together.",
    "fellowReason": "Our team comprises chefs, food bloggers, and technology enthusiasts who share a common love for food innovation.",
    "stage": "Seed",
    "applicationStatus": "Active",
    "foundersNumber": 2,
    "foundedYear": 2023,
    "region": "South Africa",
    "batch": "S23",
    "fileNamePitch": "test.pdf",
    "bucketPathPitch": "/pitches/test.pdf",
    "typePitch": "application/pdf",
    "deleted": false
  },
  {
    "name": "ArtisanCraft",
    "description": "ArtisanCraft is dedicated to preserving and promoting traditional craftsmanship through a curated marketplace.",
    "motivation": "We are passionate about preserving traditional craftsmanship and providing artisans with a platform to showcase their skills.",
    "fellowReason": "Our team comprises artisans, designers, and cultural enthusiasts who are committed to supporting artisanal communities.",
    "stage": "Idea",
    "applicationStatus": "Active",
    "foundersNumber": 3,
    "foundedYear": 2022,
    "region": "Europe",
    "batch": "W23",
    "fileNamePitch": "test.pdf",
    "bucketPathPitch": "/pitches/test.pdf",
    "typePitch": "application/pdf",
    "deleted": false
  },
  {
    "name": "TravelTech Innovations",
    "description": "TravelTech Innovations offers cutting-edge technology solutions to enhance travel experiences and streamline operations in the travel industry.",
    "motivation": "We are driven by our passion for travel and the belief that technology can revolutionize the travel industry.",
    "fellowReason": "Our team comprises travel enthusiasts, technologists, and industry experts who are committed to transforming the travel experience.",
    "stage": "SeriesC",
    "applicationStatus": "Active",
    "foundersNumber": 4,
    "foundedYear": 2021,
    "region": "Oceania",
    "batch": "S24",
    "fileNamePitch": "test.pdf",
    "bucketPathPitch": "/pitches/test.pdf",
    "typePitch": "application/pdf",
    "deleted": false
  },
  {
    "name": "Fintech Solutions",
    "description": "Fintech Solutions offers innovative financial technology products and services to empower individuals and businesses in managing their finances.",
    "motivation": "We are motivated by the belief that financial technology can democratize access to financial services and promote financial inclusion.",
    "fellowReason": "Our team comprises finance professionals, technologists, and entrepreneurs who are passionate about leveraging technology to reshape the financial landscape.",
    "stage": "SeriesB",
    "applicationStatus": "Active",
    "foundersNumber": 3,
    "foundedYear": 2020,
    "region": "America",
    "batch": "W24",
    "fileNamePitch": "test.pdf",
    "bucketPathPitch": "/pitches/test.pdf",
    "typePitch": "application/pdf",
    "deleted": false
  }
  


];